AtomCCD/AtomCCD/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login, logout

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'AtomCCD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^CCD/', include('CCD.urls', namespace='CCD')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/', login),
    url(r'^accounts/logout/', logout, {'next_page': '/CCD/'}),
    )
if settings.DEBUG:
# static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

AtomCCD/CCD/urls.py
__author__ = 'anthony.lozano'
from django.conf.urls import patterns, url

from CCD import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new_patient/added/', views.added, name='added'),
    url(r'^new_patient/', views.new_patient, name='new_patient'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^bbhr/', views.bbhr, name='bbhr'),
    url(r'^view_CCD', views.view_CCD, name='view_CCD')
)

AtomCCD/CCD/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Atom(models.Model):
    logic = models.CharField(max_length=100)  # Just a dummy until we figure this out for real
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Patient(models.Model):
    user = models.ForeignKey(User)
    chart = models.FileField()

    def __str__(self):
        return self.user.username

class Physician(models.Model):
    patients = models.ManyToManyField(Patient)

AtomCCD/CCD/forms.py
__author__ = 'anthony.lozano'
from django import forms
from tempfile import NamedTemporaryFile
from ccdaparser import parse_ccda
from django.contrib.auth.models import User
from models import Patient
import os
from django.conf import settings
import logging
class new_patient_form(forms.Form):

    ccd_file = forms.FileField()
    Email = forms.EmailField()

    def add_patient(self, ccd_file, pref_email):
        #Because of a chicken-egg problem, we need to write the CCDA to disk then have bluebutton parse it before we can
        #pass it to a model
        with NamedTemporaryFile(delete=False) as xml_file:
            for chunk in ccd_file.chunks():
                xml_file.write(chunk)
        ccda = parse_ccda(xml_file.name)
        new_user = User.objects.create_user(pref_email, pref_email, 'password')
        new_user.first_name = ccda['demographics']['name']['given'][0]
        new_user.last_name = ccda['demographics']['name']['family']
        new_user.save()
        new_patient = Patient(user=new_user, chart=ccd_file)
        new_patient.save()

class PatientForm(forms.Form):
    patient = forms.ModelChoiceField(queryset=Patient.objects.all().order_by('user'), to_field_name="user", empty_label=None)

AtomCCD/CCD/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from forms import new_patient_form, PatientForm
from models import Patient
from django.contrib.auth.decorators import login_required
from ccdaparser import parse_ccda
from django.conf import settings
import xml.etree.ElementTree as ET
from xml.etree.ElementTree import tostring
import os
from bs4 import BeautifulSoup


codes = {
    "48765-2": "allergies_reactions_alerts",
    "46240-8": "encounter_history",
    "10157-6": "family_history",
    "11369-6": "immunization_history",
    "10160-0": "medication_history",
    "11450-4": "problem_list",
    "47519-4": "procedures",
    "30954-2": "results",
    "29762-2": "social_history",
    "42348-3": "advanced_directives",
    "48768-6": "payment_sources",
    "8716-3": "physical_findings",
    "42349-1": "reason_for_referral",
    "18776-5": "treatment_plan",
    "47420-5": "functional_status",
    "29549-3": "medication_administered",
    "69730-0": "instructions",

}

# Create your views here.

def index(request):
    return render(request, 'CCD/index.html', {})

@login_required()
def new_patient(request):
    if request.method == 'POST':
        form = new_patient_form(request.POST, request.FILES)
        if form.is_valid():
            form.add_patient(request.FILES['ccd_file'], form.cleaned_data['Email'])
        else:
            raise Exception("shit!")
        return HttpResponseRedirect('added/')

    else:
        form = new_patient_form()

    return render(request, 'CCD/new_patient.html', {'form': form})

def added(request):
    return render(request, 'CCD/added.html', {})

def login(request):
    pass

@login_required
def dashboard(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            json_chart = parse_ccda(form.cleaned_data['patient'].chart.file.name)
            request.session['CurrentPatient'] = json_chart
            request.session['CurrentPatientXml'] = open(form.cleaned_data['patient'].chart.file.name).read()
            xml_root = remove_namespaces(request.session['CurrentPatientXml'])

            request.session['CurrentPatientTables'] = get_tables(xml_root)
            errors = form.errors or None # form not submitted or it has errors
            return render(request, 'CCD/dashboard.html', {'form': form, 'errors': errors, })
    form = PatientForm()
    errors = form.errors or None # form not submitted or it has errors
    return render(request, 'CCD/dashboard.html',{'form': form, 'errors': errors, })

@login_required()
def bbhr(request):
    return render(request, 'CCD/BBHR.html')

@login_required()
def view_CCD(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            json_chart = parse_ccda(form.cleaned_data['patient'].chart.file.name)
            request.session['CurrentPatient'] = json_chart
            request.session['CurrentPatientXml'] = get_stylish_tables(open(form.cleaned_data['patient'].chart.file.name).read())
            xml_root = remove_namespaces(request.session['CurrentPatientXml'])
            request.session['CurrentPatientTables'] = get_tables(xml_root)
            suffix_tag = xml_root.find("recordTarget").find("patientRole").find("patient").find('name').find("suffix")
            if suffix_tag:
                request.session['middle'] = xml_root.find("recordTarget").find("patientRole").find("patient").find('name').find("suffix").text
            elif 'middle' in request.session:
                del request.session['middle']
            errors = form.errors or None # form not submitted or it has errors
            return render(request, 'CCD/patient_summary.html', {'form': form, 'errors': errors})
    form = PatientForm()
    errors = form.errors or None # form not submitted or it has errors
    return render(request, 'CCD/patient_summary.html', {'form': form, 'errors': errors})


def get_tables(xml_root):
    """
    finds all the tables and their section titles for a CCD
    :param xml_root:
    :return:
    """
    tables = {}
    for section in xml_root.iter("section"):
        if list(section.iter("table")):
            if section.find("code"):
                tables[codes[section.find("code").attrib['code']]] = tostring(section.iter("table").next())
            else:
                tables[section.find("title").text.replace(' ', "_").replace(",", "")] = tostring(section.iter("table").next())
    return tables


def get_stylish_tables(xml):
    soup = BeautifulSoup(xml, "xml")
    tables = soup.find_all('table')
    for table in tables:
        table['class'] = "table table-striped table-bordered table-hover table-responsive"
    theads = soup.find_all('thead')
    for thead in theads:
        thead['data-sortable'] = "true"
    return str(soup)


def remove_namespaces(xml):
    """
    Returns a xml root, but strips out any namespaces from the tags.
    :type xml: xml to strip namespace from
    """
    from StringIO import StringIO
    it = ET.iterparse(StringIO(xml))
    for _, el in it:
        if '}' in el.tag:
            el.tag = el.tag.split('}', 1)[1]  # strip all namespaces
    return it.root

AtomCCD/templates/allergy.html
{% load staticfiles %}
<meta name "viewport" content "width = device-width, initial-scale = 1.0">
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.css' %}"/>
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.min.css' %}"/>
<div class = "navbar navbar-inverse"></div>  
<h1 align = "center"> Allergy History For Marla!</h1>
   <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["table"]});
      google.setOnLoadCallback(drawTable);

      function drawTable() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Allergy');
        data.addColumn('string', 'Status');
        data.addColumn('string', 'Date');
        data.addRows([
          ['Hay fever with asthma','active','N/A'],['Hives','inactive','04/23/2011']]);

        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {showRowNumber: true});
      }
    </script><div id="table_div" style="width: 100%; height: 180px;"></div>

AtomCCD/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>AtomCCD</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">

    <!-- Font Awesome CDN -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!-- Navigation bar -->
    {% include 'navbar.html' %}

    <!-- Main jumbotron for a primary marketing message or call to action
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    -->
    <div class="container">
    	{% block content %}

        {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

AtomCCD/templates/home.html
{% extends "base.html" %}

{% block content %}
<br><br>
<h2>Welcome to AtomCCD</h2>

Stuff you can do:<br>
        <ul>
            <li><a href={% url 'CCD:new_patient' %}> Add a patient </a></li>
            <!-- <li><a href={% url 'CCD:dashboard' %}> Go to Dashboard </a></li> -->
            <li><a href={% url 'CCD:view_CCD' %}> Go to Patient View </a></li>
        </ul>
{% endblock %}

AtomCCD/templates/immun.html
{% load staticfiles %}
<meta name "viewport" content "width = device-width, initial-scale = 1.0">
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.css' %}"/>
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.min.css' %}"/>
<div class = "navbar navbar-inverse"></div>  
<h1 align = "center"> Immunization History For Marla!</h1>
   <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["table"]});
      google.setOnLoadCallback(drawTable);

      function drawTable() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Vaccination');
        data.addColumn('number', 'Dose Quantity');
        data.addColumn('string', 'Unit');
        data.addColumn('string', 'Date');
        data.addRows([
          ['Influenza virus vaccine',50,'mcg','04/23/2011'],
          ['Tetanus and diphtheria toxoids - preservative free',50,'mcg','04/23/2011']]);

        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {showRowNumber: true});
      }
    </script><div id="table_div" style="width: 100%; height: 180px;"></div>

AtomCCD/templates/med.html
{% load staticfiles %}
<meta name "viewport" content "width = device-width, initial-scale = 1.0">
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.css' %}"/>
<link rel = "stylesheet" type ="text/css" href ="{% static 'heathapp/css/bootstrap.min.css' %}"/>
<div class = "navbar navbar-inverse"></div>  
<h1 align = "center"> Medication History For Marla!</h1>
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization',
       'version':'1','packages':['timeline']}]}"></script>
<script type="text/javascript">
google.setOnLoadCallback(drawChart);

function drawChart() {
  var container = document.getElementById('example1');

  var chart = new google.visualization.Timeline(container);

  var dataTable = new google.visualization.DataTable();
  

  
  dataTable.addColumn({ type: 'string', id: 'President' });
  dataTable.addColumn({ type: 'date', id: 'Start' });
  dataTable.addColumn({ type: 'date', id: 'End' });

  dataTable.addRows([['Furosemide 40 MG Oral Tablet [Lasix]',new Date(2011, 4, 23),new Date(2012, 4, 23)],
['24 HR Propranolol Hydrochloride 60 MG Extended Release Oral Capsule [Inderal]', new Date(2011, 4, 23), new Date(2012, 4, 23)],
['Furosemide 40 MG Oral Tablet [Lasix]', new Date(2012, 4, 25), new Date(2013,4,25)],
['24 HR Propranolol Hydrochloride 60 MG Extended Release Oral Capsule [Inderal]', new Date(2012, 4, 25), new Date(2013, 4, 25)]])
  
  chart.draw(dataTable);
}
</script>
<div id="example1" style="width: 100%; height: 180px;"></div>
{% if latest_question_list %}
    
<p>{{"place holder"}} </p>

{% else %}
    <p>No polls are available.</p>
{% endif %}

<div id="demo"> </div>

AtomCCD/templates/navbar.html
{% load ccd_extras %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href= {% url 'CCD:index' %}>AtomCCD</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      {% if user.is_authenticated %}
      <div id="navbar-welcome" class="navbar-text navbar-left">
       <form enctype="multipart/form-data" action="/CCD/view_CCD/" class="navbar-form navbar-left" role="form" method="post">
         {% csrf_token %}
          <div class="form-group">
            {% patient_form %}
           </div>
         <div class="form-group">
          <input type="submit" value="Select" class="btn btn-success btn-xs"/>
         </div>
       </form>
      </div>
      <div id="navbar-welcome" class="navbar-text navbar-right"> Welcome, {{ user.username }}.  <a href="/accounts/logout">logout</a> </div>

      {% else %}
      <form class="navbar-form navbar-right" role="form" action="/accounts/login/" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input id="id_username" maxlength="254" name="username" type="text"  placeholder="Email" class="form-control" />
        </div>
        <div class="form-group">
          <input id="id_password" name="password" type="password" placeholder="Password" class="form-control" />
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
        <input type="hidden" name="next" value="{{ request.get_full_path }}" />
      </form>
      {% endif %}
    </div><!--/.navbar-collapse -->
  </div>
</nav>